version: '3'

volumes:
  postgres_data_keycloak:
      driver: local

services:
  postgres:
      restart: always
      image: postgres
      volumes:
        - postgres_data_keycloak:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: Y4S@uN6%
      ports:
        - 5432
  keycloak:
      restart: always
      image: quay.io/keycloak/keycloak:legacy
      environment:
        KEYCLOAK_IMPORT: /tmp/SafeNetOtpRealm.json        
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_SCHEMA: public
        DB_PASSWORD: Y4S@uN6%
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: Y4S@uN6%
        # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
        #JDBC_PARAMS: "ssl=true"
      ports:
        - 8080:8080
        - 8443:8443
      depends_on:
        - postgres